MatchPointMasters/MatchPointMasters/Areas/Admin/Controllers/UserController.cs
namespace MatchPointMasters.Areas.Admin.Controllers
{
    using MatchPointMasters.Core.Contracts;
    using MatchPointMasters.Core.Models.Admin.QueryModels;
    using MatchPointMasters.Infrastructure.Data.Models.Roles;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using static MatchPointMasters.Core.Constants.AdministratorConstants;
    using static System.Security.Claims.ClaimsPrincipalsExtension;
    public class UserController : AdminBaseController
    {

        private readonly UserManager<ApplicationUser> userManager;
        private readonly IUserService userService;
        private readonly ITournamentHostService tournamentHostService;
        private readonly IAdminService adminService;

        public UserController(UserManager<ApplicationUser> _userManager, IUserService _userService, ITournamentHostService _tournamentHostService, IAdminService _adminService)
        {
            userManager = _userManager;
            userService = _userService;
            tournamentHostService = _tournamentHostService;
            adminService = _adminService;
        }

        [HttpGet]
        public async Task<IActionResult> All([FromQuery] AllUsersQueryModel model)
        {
            var allUsers = await userService.AllAsync(
                User.Id(),
                model.SearchTerm,
                model.RoleStatus,
                model.CurrentPage,
                model.UsersPerPage);

            model.TotalUsersCount = allUsers.TotalUsersCount;
            model.Users = allUsers.Users;

            return View(model);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Details(string userId)
        {
            var user = await userService.GetUserByIdAsync(userId);

            if (user == null)
            {
                return BadRequest();
            }

            var currentUserDetails = await userService.DetailsAsync(userId);

            return View(currentUserDetails);
        }

        [HttpGet]
        public async Task<IActionResult> AddTournamentHost(string id)
        {
            if (!User.IsAdmin())
            {
                return Unauthorized();
            }
            if (!await userService.ExistsByIdAsync(id))
            {
                return BadRequest();
            }
            else if (await tournamentHostService.ExistsByUserIdAsync(id))
            {
                return RedirectToAction(nameof(All));
            }

            var user = await userService.GetUserByIdAsync(id);

            var hostForm = new UserServiceModel()
            {
                Id = id,
                FullName = userService.UserFullNameAsync(id).Result,
                Email = user.Email,
                IsTournamentHost = tournamentHostService.ExistsByUserIdAsync(id).Result,
                IsAdmin = userManager.IsInRoleAsync(user, AdminRole).Result
            };

            return View(hostForm);
        }

        [HttpPost]
        public async Task<IActionResult> AddTournamentHostConfirmed(string id)
        {
            if (!User.IsAdmin())
            {
                return Unauthorized();
            }
            if (!await userService.ExistsByIdAsync(id))
            {
                return BadRequest();
            }
            else if (await tournamentHostService.ExistsByUserIdAsync(id))
            {
                return RedirectToAction(nameof(All));
            }

            await adminService.AddTournamentHostAsync(id);
            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<IActionResult> RemoveTournamentHost(string id)
        {
            if (!User.IsAdmin())
            {
                return Unauthorized();
            }
            if (!await userService.ExistsByIdAsync(id))
            {
                return BadRequest();
            }
            else if (!await tournamentHostService.ExistsByUserIdAsync(id))
            {
                return RedirectToAction(nameof(All));
            }

            var user = await userService.GetUserByIdAsync(id);

            var hostForm = new UserServiceModel()
            {
                Id = id,
                FullName = userService.UserFullNameAsync(id).Result,
                Email = user.Email,
                IsTournamentHost = tournamentHostService.ExistsByUserIdAsync(id).Result,
                IsAdmin = userManager.IsInRoleAsync(user, AdminRole).Result
            };

            return View(hostForm);
        }

        [HttpPost]
        public async Task<IActionResult> RemoveTournamentHostConfirmed(string id)
        {
            if (!User.IsAdmin())
            {
                return Unauthorized();
            }
            if (!await userService.ExistsByIdAsync(id))
            {
                return BadRequest();
            }
            else if (!await tournamentHostService.ExistsByUserIdAsync(id))
            {
                return RedirectToAction(nameof(All));
            }

            await adminService.RemoveTournamentHostConfirmedAsync(id);

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<IActionResult> AddAdmin(string id)
        {
            if (!User.IsAdmin())
            {
                return Unauthorized();
            }
            if (!await userService.ExistsByIdAsync(id))
            {
                return BadRequest();
            }

            var user = await userService.GetUserByIdAsync(id);

            if (await userManager.IsInRoleAsync(user, AdminRole))
            {
                return RedirectToAction(nameof(All));
            }

            var adminForm = new UserServiceModel()
            {
                Id = id,
                FullName = userService.UserFullNameAsync(id).Result,
                Email = user.Email,
                IsTournamentHost = tournamentHostService.ExistsByUserIdAsync(id).Result,
                IsAdmin = userManager.IsInRoleAsync(user, AdminRole).Result
            };

            return View(adminForm);
        }

        [HttpPost]
        public async Task<IActionResult> AddAdminConfirmed(string id)
        {
            if (!User.IsAdmin())
            {
                return Unauthorized();
            }
            if (!await userService.ExistsByIdAsync(id))
            {
                return BadRequest();
            }

            var user = await userService.GetUserByIdAsync(id);

            if (await userManager.IsInRoleAsync(user, AdminRole))
            {
                return RedirectToAction(nameof(All));
            }

            await adminService.AddAdminAsync(id);
            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<IActionResult> RemoveAdmin(string id)
        {
            if (!User.IsAdmin())
            {
                return Unauthorized();
            }
            if (!await userService.ExistsByIdAsync(id))
            {
                return BadRequest();
            }

            var user = await userService.GetUserByIdAsync(id);

            if (!await userManager.IsInRoleAsync(user, AdminRole))
            {
                return RedirectToAction(nameof(All));
            }

            var adminForm = new UserServiceModel()
            {
                Id = id,
                FullName = userService.UserFullNameAsync(id).Result,
                Email = user.Email,
                IsTournamentHost = tournamentHostService.ExistsByUserIdAsync(id).Result,
                IsAdmin = userManager.IsInRoleAsync(user, AdminRole).Result
            };

            return View(adminForm);
        }

        [HttpPost]
        public async Task<IActionResult> RemoveAdminConfirmed(string id)
        {
            if (!User.IsAdmin())
            {
                return Unauthorized();
            }
            if (!await userService.ExistsByIdAsync(id))
            {
                return BadRequest();
            }

            var user = await userService.GetUserByIdAsync(id);

            if (!await userManager.IsInRoleAsync(user, AdminRole))
            {
                return RedirectToAction(nameof(All));
            }

            await adminService.RemoveAdminConfirmedAsync(id);

            return RedirectToAction(nameof(All));
        }


    }
}

MatchPointMasters/MatchPointMasters/Controllers/ArticleController.cs
namespace MatchPointMasters.Controllers
{
    using MatchPointMasters.Core.Contracts;
    using MatchPointMasters.Extensions;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using MatchPointMasters.Core.Extensions;
    using MatchPointMasters.Attributes;
    using MatchPointMasters.Core.Models.Article.QueryModels;
    using MatchPointMasters.Core.Models.Article.ViewModels;
    using System.Security.Claims;

    public class ArticleController : BaseController
    {

        private readonly IArticleService articleService;
        private readonly ITournamentHostService tournamentHostService;

        public ArticleController(IArticleService _articleService, ITournamentHostService _tournamentHostService)
        {
            articleService = _articleService;
            tournamentHostService = _tournamentHostService;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> All([FromQuery] AllArticlesQueryModel model)
        {
            var allArticles = await articleService.AllAsync(
                model.SearchTerm,
                model.Sorting,
                model.CurrentPage,
                model.ArticlesPerPage);

            model.TotalArticlesCount = allArticles.TotalArticlesCount;
            model.Articles = allArticles.Articles;
            
            return View(model);
        }

		[HttpGet]
		[AllowAnonymous]
		public async Task<IActionResult> Details(int id, string information)
		{
			if (!await articleService.ArticleExistsAsync(id))
			{
				return BadRequest();
			}

			var currentArticle = await articleService.DetailsAsync(id);

			if (information != currentArticle.GetInformation())
			{
				return BadRequest();
			}

			return View(currentArticle);
		}

		[HttpGet]
		[MustBeATournamentHost]
		public async Task<IActionResult> Add()
		{
			if (await tournamentHostService.ExistsByUserIdAsync(User.Id()) == false)
			{
				return Unauthorized();
			}

			var articleForm = new ArticleAddViewModel();

			return View(articleForm);
		}

		[HttpPost]
		[MustBeATournamentHost]
		public async Task<IActionResult> Add(ArticleAddViewModel articleForm)
		{
			if (await tournamentHostService.ExistsByUserIdAsync(User.Id()) == false)
			{
				return Unauthorized();
			}
			if (!ModelState.IsValid)
			{
				return View(articleForm);
			}
			
			await articleService.AddAsync(articleForm);
			return RedirectToAction(nameof(All));
		}

		[HttpGet]
		[MustBeATournamentHost]
		public async Task<IActionResult> Edit(int id)
		{
			if (!await articleService.ArticleExistsAsync(id))
			{
				return BadRequest();
			}

			var articleForm = await articleService.EditGetAsync(id);
			return View(articleForm);
		}

		[HttpPost]
		[MustBeATournamentHost]
		public async Task<IActionResult> Edit(ArticleEditViewModel articleForm)
		{
			if (articleForm == null)
			{
				return BadRequest();
			}

			if (!ModelState.IsValid)
			{
				return View(articleForm);
			}

			int id = articleForm.Id;
			await articleService.EditPostAsync(articleForm);
			return RedirectToAction(nameof(Details), new { id, information = articleForm.GetInformation() });
		}

		[HttpGet]
		[MustBeATournamentHost]
		public async Task<IActionResult> Delete(int id)
		{
			if (!await articleService.ArticleExistsAsync(id))
			{
				return BadRequest();
			}

			var searchedArticle = await articleService.DeleteAsync(id);

			return View(searchedArticle);
		}

		[HttpPost]
		[MustBeATournamentHost]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			if (!await articleService.ArticleExistsAsync(id))
			{
				return BadRequest();
			}

			await articleService.DeleteConfirmedAsync(id);

			return RedirectToAction(nameof(All));
		}

		[AllowAnonymous]
		[HttpGet]
		public async Task<IActionResult> AllComments(int id, [FromQuery] AllArticleCommentsQueryModel model)
		{
			var article = articleService.FindArticleByIdAsync(id).Result;
			var articleInfo = await articleService.DetailsAsync(id);

			var allArticleComments = await articleService.AllArticleCommentsAsync(
				id,
				article.Title,
				model.SearchTerm,
				model.Sorting,
				model.CurrentPage,
				model.CommentsPerPage);

			model.TotalArticleCommentsCount = allArticleComments.TotalArticleCommentsCount;
			model.ArticleComments = allArticleComments.ArticleComments;
			model.ArticleId = id;
			model.ArticleTitle = article.Title;
			model.ArticleInfo = articleInfo.GetInformation();

			return View(model);
		}

		[HttpGet]
		public async Task<IActionResult> AddComment(int id)
		{
			string userId = User.Id();

			var articleCommentForm = new ArticleCommentAddViewModel()
			{
				ArticleId = id,
				UserId = userId
			};

			return View(articleCommentForm);
		}

		[HttpPost]
		public async Task<IActionResult> AddComment(ArticleCommentAddViewModel articleCommentForm)
		{
			if (!ModelState.IsValid)
			{
				return View(articleCommentForm);
			}

			int newArticleComment = await articleService.AddArticleCommentAsync(articleCommentForm, articleCommentForm.UserId, articleCommentForm.ArticleId);

			return RedirectToAction(nameof(AllComments), new { id = articleCommentForm.ArticleId });
		}

		[HttpGet]
		public async Task<IActionResult> EditComment(int id)
		{
			var comment = await articleService.FindArticleCommentByIdAsync(id);

			if (comment == null)
			{
				return BadRequest();
			}
			if (User.Id() != comment.UserId)
			{
				return Unauthorized();
			}

			var commentForm = await articleService.EditArticleCommentGetAsync(id);
			return View(commentForm);
		}

		[HttpPost]
		public async Task<IActionResult> EditComment(ArticleCommentEditViewModel commentForm)
		{
			if (commentForm == null)
			{
				return BadRequest();
			}
			if (User.Id() != commentForm.UserId)
			{
				return Unauthorized();
			}
			if (!ModelState.IsValid)
			{
				return View(commentForm);
			}

			await articleService.EditArticleCommentPostAsync(commentForm);
			return RedirectToAction(nameof(AllComments), new { id = commentForm.ArticleId });
		}

		[HttpGet]
		public async Task<IActionResult> DeleteComment(int id)
		{
			var articleComment = await articleService.FindArticleCommentByIdAsync(id);

			if (articleComment == null)
			{
				return BadRequest();
			}
			if (articleComment.UserId != User.Id())
			{
				return Unauthorized();
			}

			var searchedArticleComment = await articleService.DeleteArticleCommentAsync(id);

			return View(searchedArticleComment);
		}

		[HttpPost]
		public async Task<IActionResult> DeleteCommentConfirmed(int commentId)
		{
			var bookReview = await articleService.FindArticleCommentByIdAsync(commentId);

			if (bookReview == null)
			{
				return BadRequest();
			}
			if (bookReview.UserId != User.Id())
			{
				return Unauthorized();
			}


			return RedirectToAction(nameof(AllComments), new { id = await articleService.DeleteArticleCommentConfirmedAsync(commentId) });
		}
	}

}

MatchPointMasters/MatchPointMasters/Controllers/ClubController.cs
using MatchPointMasters.Core.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace MatchPointMasters.Controllers
{
    public class ClubController : BaseController
    {
        private readonly IClubService clubService;

        public ClubController(IClubService _clubService)
        {
            clubService = _clubService;
        }

        public async Task<IActionResult> All()
        {
            var allClubs = await clubService.AllAsync();
            return View(allClubs);
        }
    }
}

MatchPointMasters/MatchPointMasters/Views/Shared/_ArticleCommentPartial.cshtml
@inject UserManager<ApplicationUser> UserManager
@model ArticleCommentServiceModel

@{
    var user = await UserManager.FindByIdAsync(Model.UserId);
    var currentUserName = user?.UserName;
}

<div style="border: 1px solid #ccc; padding: 10px; margin-bottom: 10px;">
    <div><strong>@currentUserName</strong></div>
    <div><strong>Заглавие:</strong> @Model.Title</div>
    <div><strong>Описание:</strong> @Model.Description</div>

    <div class="d-flex justify-content-center mt-3">
        @if (Model.UserId == UserManager.GetUserId(User))
        {
                <a asp-controller="Article" asp-action="EditComment" asp-route-id="@Model.Id" class="btn btn-secondary px-2 fw-bold me-2">Редактирай</a>
                <a asp-controller="Article" asp-action="DeleteComment" asp-route-id="@Model.Id" class="btn btn-danger px-2 fw-bold">Изтрий</a>
        }
    </div>
</div>

MatchPointMasters/MatchPointMasters/Views/Shared/_ArticlePagesPartial.cshtml
@model AllArticlesQueryModel

@{
    var previousPage = Model.CurrentPage - 1;
    if (previousPage < 1)
    {
        previousPage = 1;
    }

    var maxPage = Math.Ceiling((double)Model.TotalArticlesCount /
        Model.ArticlesPerPage);
}

@{
    var shouldButtonBeDisabled = Model.CurrentPage == maxPage || !Model.Articles.Any();
}

<div class="row justify-content-center mt-2">
    <div class="col-md-6 d-flex justify-content-between">
        <a class="btn btn-primary @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
           asp-controller="Article"
           asp-action="All"
           asp-route-currentPage="@previousPage"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-sorting="@((int)Model.Sorting)"><<</a>

        <p class="align-self-center">Страница @Model.CurrentPage от @maxPage</p>

        <a class="btn btn-primary @(shouldButtonBeDisabled ? "disabled" : string.Empty)"
           asp-controller="Article"
           asp-action="All"
           asp-route-currentPage="@(Model.CurrentPage + 1)"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-sorting="@((int)Model.Sorting)">>></a>
    </div>
</div>

MatchPointMasters/MatchPointMasters/Views/Shared/_ArticlePartial.cshtml
@model ArticleServiceModel

@{
    CultureInfo.CurrentCulture = new System.Globalization.CultureInfo("en-EN");
}

<div class="col-lg-4 col-md-6 col-sm-12 mb-4">
    <div class="card h-100 text-center">
        <img class="card-img-top" src="@Model.ImageUrl" alt="Article Image">
        <div class="card-body">
            <h4 class="card-title"><strong>@Model.Title</strong></h4>
            <p class="card-text"><strong>Публикувана:</strong> @Model.DatePublished.ToString("dd/MM/yyyy")</p>
            <p class="card-text"><strong>Прочитания:</strong> @Model.ViewsCount</p>
        </div>
        <a asp-controller="Article" asp-action="Details" asp-route-id="@Model.Id" asp-route-information="@Model.GetInformation()" class="btn btn-warning mb-1 w-100 p-3 fw-bold">Прочети повече</a>
    </div>
</div>

MatchPointMasters/MatchPointMasters/Views/Shared/_ClubPartial.cshtml
@model ClubServiceModel

<div class="card" id="club-card">
    <img src="@Model.ImageUrl" class="tournamentImage" alt="@Model.Name">
    <div class="card-body">
        <h5 class="card-title">@Model.Name</h5>
        <p class="card-text">Surface: @Model.CourtSurface.ToString()</p>
        <hr />
        <a asp-area="" asp-controller="Club" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-primary">Details</a>
    </div>
</div>

MatchPointMasters/MatchPointMasters/Views/Shared/_Layout.cshtml
@using MatchPointMasters.Components
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Match Point Masters for tennis lovers and ninjas!</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MatchPointMasters.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Match^Point^Masters</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @await Component.InvokeAsync(nameof(MainMenuComponent))
                    <ul class="navbar-nav">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            @* <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Match" asp-action="All" asp-route-id="@UserManager.GetUserId(User)">Моите мачове</a>
                            </li> *@
                        }
                        @if (User.IsAdmin())
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="User" asp-action="All" title="Admin">Действия</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.UtcNow.Year - MatchPointMasters League for tennis enthusiasts :)
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MatchPointMasters/MatchPointMasters/Views/Shared/_MatchPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

MatchPointMasters/MatchPointMasters/Views/Shared/_PlayerPartial.cshtml
@model PlayerServiceModel
@inject UserManager<ApplicationUser> UserManager


<div class="playerProfileBody">
    <div id="wrapper">
        <div id="avatar">
            <img src="@Model.ImageUrl" alt="@UserManager.GetUserName(User)" class="playerImage">
        </div>
        <div class="user-info">
            <div id="main-info">
                <h1> @UserManager.GetUserName(User)<br />@Model.DominantHand.ToString()</h1>
                <a asp-area="" asp-controller="player" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-success">See more</a>
            </div>
        </div>
    </div>
</div>

MatchPointMasters/MatchPointMasters/Views/Shared/_SetPartial.cshtml
@model SetServiceModel

<div class="col mb-4">
    <div class="card h-100 text-center">
        <div class="card-body">
            <h4 class="card-title"><strong>@Model.Id</strong></h4>
            <p class="card-text"> @Model.PlayerOneGamesWon / @Model.PlayerTwoGamesWon</p>
        </div>
        <a asp-controller="Set" asp-action="Details" asp-route-information="@Model.GetInformation()" asp-route-id="@Model.Id" class="btn btn-warning mb-1 w-100 p-3 fw-bold">Виж Повече</a>
    </div>
</div>

MatchPointMasters/MatchPointMasters/Views/Shared/_TiebreakPartial.cshtml
@model TiebreakServiceModel

<div class="col mb-4">
    <div class="card h-100 text-center">
        <div class="card-body">
            <h4 class="card-title"><strong>@Model.Id</strong></h4>
            <p class="card-text"> @Model.PlayerOnePoints / @Model.PlayerTwoPoints</p>
        </div>
        <a asp-controller="Tiebreak" asp-action="Details" asp-route-information="@Model.GetInformation()" asp-route-id="@Model.Id" class="btn btn-warning mb-1 w-100 p-3 fw-bold">Виж Повече</a>
    </div>
</div>

MatchPointMasters/MatchPointMasters/Views/Shared/_TournamentPagesPartial.cshtml
@model AllTournamentsQueryModel

@{
    var previousPage = Model.CurrentPage - 1;
    if (previousPage < 1)
    {
        previousPage = 1;
    }

    var maxPage = Math.Ceiling((double)Model.TotalTournamentsCount /
        Model.TournamentsPerPage);
}

@{
    var shouldButtonBeDisabled = Model.CurrentPage == maxPage || !Model.Tournaments.Any();
}

<div class="row justify-content-center mt-2">
    <div class="col-md-6 d-flex justify-content-between">
        <a class="btn btn-primary @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
           asp-controller="Tournament"
           asp-action="All"
           asp-route-currentPage="@previousPage"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-sorting="@((int)Model.Sorting)"><<</a>

        <p class="align-self-center">Страница @Model.CurrentPage от @maxPage</p>

        <a class="btn btn-primary @(shouldButtonBeDisabled ? "disabled" : string.Empty)"
           asp-controller="Tournament"
           asp-action="All"
           asp-route-currentPage="@(Model.CurrentPage + 1)"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-sorting="@((int)Model.Sorting)">>></a>
    </div>
</div>

MatchPointMasters/MatchPointMasters/Views/Shared/_TournamentPartial.cshtml
@model TournamentServiceModel

@{
    CultureInfo.CurrentCulture = new System.Globalization.CultureInfo("en-EN");
}

<div class="card mb-4">
    <img class="card-img-top" src="@Model.ImageUrl" alt="Tournament Image">
    <div class="card-body">
        <h4 class="card-title"><strong>@Model.Name</strong></h4>
        <p class="card-text"><strong>Локация:</strong> @Model.HostClub</p>
        <p class="card-text">
            <strong>Начало:</strong> @Model.StartDate.ToString("dd/MM/yyyy HH:mm")
        </p>
        <p class="card-text">
            <strong>Край:</strong> @Model.EndDate.ToString("dd/MM/yyyy HH:mm")
        </p>
        <p class="card-text"><strong>Максимален брой участници:</strong> @Model.Capacity</p>
        <p class="card-text"><strong>Такса:</strong> @Model.Fee лв.</p>
        @if (Model.Capacity < 10 && Model.Capacity > 0)
        {
            <h5 class="card-text text-danger"><strong>ПОСЛЕДНИ МЕСТА В ТУРНИРА!</strong> Заяви участие преди да са свършили!</h5>
        }
    </div>
    <a asp-controller="Tournament" asp-action="Details" asp-route-id="@Model.Id" asp-route-information="@Model.GetInformation()" class="btn btn-warning mb-1 w-100 p-3 fw-bold">Виж повече</a>
    <form asp-controller="Tournament" asp-action="RegisterInTournament" method="post">
        <input type="hidden" name="id" value="@Model.Id" />
        <button type="submit" class="btn btn-success mb-1 w-100 p-3 fw-bold">Заяви участие</button>
    </form>
</div>